version: '3'

services:
  frp:
    image: jacksun/frps-docker:latest
    container_name: frps-docker
    ports:
      - "7000:7000"
      - "7500:7500"
      - "8080:80/tcp"
      - "8443:443/tcp"
    expose:
      - 8080
      - 443
    volumes:
      - frp_conf:/var/frp/conf
    restart: always
    environment:
      VIRTUAL_HOST: '*.frp.mallbear.com,frp.mallbear.com'

volumes:
    frp_conf: