version: '3'

services:
  frp:
    image: jacksun/frps-docker:latest
    container_name: frps-docker
    ports:
      - "7000:7000"
      - "7500:7500"
      - "7080:80/tcp"
      - "7443:443/tcp"
    expose:
      - 7080
      - 7443
    volumes:
      - frp_conf:/var/frp/conf
    restart: always
    environment:
      VIRTUAL_HOST: '*.frp.example.com,frp.example.com'

volumes:
    frp_conf: